name: Build and Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install backend dependencies
              run: npm install
              working-directory: ./backend

            - name: Install frontend dependencies
              run: npm install
              working-directory: ./frontend

            - name: Test frontend
              run: npm test
              working-directory: ./frontend

            - name: Build frontend
              run: npm run build
              working-directory: ./frontend
