name: Neo Tokyo Lore Generator CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    # Build backend
    build-backend:
        name: Build Backend Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build backend Docker image
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: goldensun/neo-tokyo-lore-generator-backend:latest
              # run: |
              #     docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/neo-tokyo-lore-generator-backend:latest --push ./backend

    # Build frontend
    build-frontend:
        name: Build Frontend Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build frontend Docker image
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: goldensun/neo-tokyo-lore-generator-frontend:latest
              # run: |
              #     docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/neo-tokyo-lore-generator-frontend:latest --push ./frontend
